### ISSUE TITLE
How did you created .csv file for a specific model, what values it contains

### ISSUE THREAD

**Issue by VK1995** [PeizhiShi/MsvNet#2]
We are working on multi feature recognition and using MsvNet for that.

I have downloaded dataset 'data' from [here](https://onedrive.live.com/?authkey=%21APomIKnOJnsl0Dg&cid=0A75588260A154DE&id=A75588260A154DE%21105&parId=root&action=locate)

This dataset contains directories as 'set1', 'set2', ....., 'set10' . Each set has models with multiple features with STL and binvox formats.

Each set contains csv file for each model in sets.

```python
trul = get_lvec(vis.get_label('data/set'+str(sidx)+'/'+str(idx)+'.csv',0)[:,6]).astype(int)
print('True labels:\t\t',trul)
``` 
These snippet from 'lins.multi.py' from your project reads csv file and returns array of 0 & 1 in length of 24.  1 is for recognized feature.

After testing some models I conclude that these true labels from csv are accurate. Great work!

Can you guys elaborate, 
 1. How to create that csv file?
 2. What values does csv contains? (I found that last value of each line in the csv is index of recognized feature)
 3. How should I improve predicted labels towards accuracy?

Thanks in advance.

**Comment by PeizhiShi** [comment]
1. Each intersecting model and its corresponding ground truth information (i.e. *.csv) was constructed via Solidworks API.
2. Each csv file contains the ground truth information of each STL model. For instance, there are 10 features in the 'set10/999.stl'. Therefore, there are 10 rows in the corresponding csv file. In each row, the first 6 columns refer to the coordinates of the ground truth bounding box for the feature (i.e. x, y, z_min, x, y, z_max), while the 7th column refers to the feature type. This file is used to test whether the predicted result and ground truth are matched with each other.
3. Our [recent work](https://github.com/PeizhiShi/SsdNet) published on IEEE TII  yields better results than the MsvNet.

Hope it answers your question.

**Comment by VK1995** [comment]
I appreciate your recent work!
